<?php include('includes/Header.php') ?>

<body>
    <div class="container margin">
        <form action="addstamp/submit" method="post" enctype="multipart/form-data">

            <div class="field">
                <div class="file has-name is-fullwidth">
                    <label class="file-label">
                        <input class="file-input" type="file" name="file">
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Upload Stamp
                            </span>
                        </span>
                        <span class="file-name">
                            <script>
                            let filename = document.querySelector('.file-name');
                            document.querySelector('.file-input').onchange = function() {
                                let realFileName = this.value.split('\\');

                                for (let i = 0; i < realFileName.length; i++) {
                                    if (realFileName[i].includes(".jpg")) {
                                        filename.innerHTML = realFileName[i];
                                    }
                                }
                            }
                            </script>
                        </span>
                    </label>
                </div>
            </div>

            <div class="field">
                <label class="label">Stamp Name</label>
                <div class="control">
                    <input class="input" type="text" name="name">
                </div>
            </div>

            <div class="field">
                <label class="label">Year</label>
                <div class="control">
                    <input class="input" type="text" name="year">
                </div>
            </div>

            <div class="field">
                <label class="label">Quantity</label>
                <div class="control">
                    <input class="input" type="text" name="quantity">
                </div>
            </div>

            <div class="field">
                <label class="label">Collection</label>
                <div class="control">
                    <input class="input" type="text" name="collection">
                </div>
            </div>


            <div class="field">
                <label class="label">Description</label>
                <div class="control">
                    <textarea class="textarea" placeholder="Stamp Description" name="description"></textarea>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-link">Submit</button>
                </div>
            </div>
        </form>
    </div>

</body>

<?php include('includes/Footer.php') ?>