<?php include('includes/Header.php') ?>
<a class="btn right black" href="<?= '../stamps'; ?>">Go back </a>




<section>

    <div id="new-stamp" class="card" style="overflow:scroll;">

        <h3>Update Stamp</h3>
       
        <div class="row">
            <form action="saveupdate" method="post" class="col s12 m10">
            <div class="row">
              
                    <div class="input-field col s12 m8">
                        <input type="text" name="id" value=' <?php echo $stamps->id_stamp; ?> ' readonly >
                        <label>ID</label>
                    </div>
                </div>
                <!--
                <div class="row">
                    <div class="input-field col s12 m8">
                        <input type="text" name="number" value=' <?php echo $stamps->number; ?> ' required>
                        <label>Number</label>
                    </div>
                </div>
              -->
                <div class="row">
                    <div class="input-field col s12 m8">
                        <input type="text" name="name" value=' <?php echo $stamps->name; ?> ' required>
                        <label>Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m8">
                        <input type="text" name="term" value=' <?php echo $stamps->term; ?> ' required>
                        <label>Term of Office</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m8">
                        <input type="text" name="party" value=' <?php echo $stamps->party; ?> ' required>
                        <label>Party</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12 m8">
                        <label>Description</label>
                        <textarea id="textarea1" class="materialize-textarea" name="description" required> <?php echo $stamps->description; ?> </textarea>
                    </div>
                </div>
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>
    </div>
    </div>
    <?php include('includes/Footer.php') ?>